gg:
  jte:
    templateLocation: src/main/kotlin
    templateSuffix: .jte
    developmentMode: true

spring:
  view-component:
    local-development: true
    view-action:
      enabled: true
logging:
  level:
    root: info